Create obsidian-di-tr4v4.link
cartabinaria/algebra-e-geometria pull request #12
Opened 2024-03-09 23:20 UTC by tr4v4

2024-03-10 13:58 UTC, samuelemusiani requested changes
Ciao, grazie per aver contribuito con i tuoi appunti!

Vorrei chiederti però di non inserire link a risorse esterne ma piuttosto caricare direttamente i markdown che puoi esportare molto semplicemente da obsidian. Sulla [nostra wiki](https://csunibo.students.cs.unibo.it/wiki/raccolte-di-risorse/) è presente una sezione che riguarda l'aggiunta di risorse in cui esplicitiamo questa preferenza:

> di caricare, se possibile, la risorsa stessa anziché un collegamento a una sua versione esterna: in questo modo rendi possibile ad altre persone ampliarla e correggerla in futuro.

Inoltre vorrei aggiungere che i link esterni sono estremamente fragili, e con il tempo la probabilità che si rompano cresce esponenzialmente. È già successo infatti che i link che portavano a risorse esterne abbiano smesso di funzionare e colui che li aveva caricati non è più reperibile per correggere.

Ti chiederei quindi di modificare tutte le PR che hai fatto e sostituire il link ai markdown originali.

Grazie
Samuele

2024-03-10 14:46 UTC, tr4v4 commented
Ciao! Il sito è collegato direttamente alla [repository](https://github.com/tr4v4/uni.git) di Github che è a sua volta connessa al mio vault su Obsidian, per cui pensavo di mantenerlo "chiuso" fino a che non sistemo per bene gli appunti per evitare conflitti, ovvero almeno fino alla fine del primo anno, ma se si vogliono fare delle modifiche la repository è pubblica, e nella home c'è il tasto in alto a destra con cui arrivarci, magari lo indico meglio nel sito👍.

2024-03-10 17:01 UTC, samuelemusiani commented
Ciao, il problema con il link esterno purtroppo persiste.

La nostra intenzione è di costruire un'infrastuttura per la raccolta di appunti che sia il meno possibile legata a risorse esterne che non possiamo controllare direttamente. I link a risorse esterne possono rompersi per un cambio di nome, di sito, di account e di miliardi di altri fattori che purtroppo non sono facilmente prevenibili. Se i markdown fossero caricati direttamente sulla repo l'unico modo per cui possano essere rimossi o compromessi è attraverso un futuro commit, che però siamo perfettamente in grado di controllare e sapere quando avviene. Un link esterno si rompe inaspettatamente (come già successo più volte) e non è risolvibile senza l'intervento dell'autore originale. Se quindi tra qualche anno, quando non sarai più all'università, il link si rompesse, i manutentori del futuro non potrebbero fare altro che rimuoverloe avremmo perso i tuoi appunti. Se alcuni file non sono conclusi puoi aspettare a caricarli. L'autore originale rimarrai sempre tu in quanto la history di git non verrà alterata. 

Noi crediamo fortemente che i link esterni debbano essere evitati ove possibile, soprattutto quando farlo richiede uno sforzo molto contenuto. Se hai delle motivazioni valide che non ho citato per preferire il link alla risorsa direttamente sono aperto a un confronto.

2024-03-10 18:54 UTC, Flecart commented
Sono d'accordo, però c'è da notare che i markdown presi da Obsidian non sono direttamente utilizzabili da markdown. (quindi c'è bisogno di qualche sforzo per convertirli).
sarebbe comodo fare uno script condiviso per esportare da Obsidian.
Una googlata veloce, sembra questo potrebbe risultare utile https://github.com/zoni/obsidian-export.

2024-03-10 18:55 UTC, Flecart commented
Comunque GG per @tr4v4 che fa il second brain.

2024-03-15 17:55 UTC, tr4v4 commented
Ciao @samuelemusiani, scusa se sono sparito. Va bene mi hai convinto, ma visto che la repository con i markdown c'è già non c'è un modo facile per collegare le due repository così da avere tutto sempre sincronizzato? So che per esempio con [Zapier](https://zapier.com) si potrebbe creare un automatismo che ad ogni mio push sulla mia repository venga creata una pull request su questa di csunibo. Se chiedo tanto e non c'è un modo più semplice per farlo allora carico intanto i file che ho ora, poi ogni tot. pusho con le modifiche. In effetti i markdown di Obsidian senza Obsidian sono poco utili @Flecart, se si preferisce avere markdown "normali" allora uso [Obsidian export](https://github.com/zoni/obsidian-export) per convertirli prima di caricarli. E grazie per il second brain🧠

2024-03-15 19:24 UTC, Flecart commented
Supponendo che le note le fai ad ogni lezione non credo sia ragionevole reviewware e mergiare PR ogni giorno.

Sarebbe più sensato darti write permission su tutto, oppure che tu carichi solo appunti vecchi, che ne dici @samuelemusiani ?

Se vogliamo andare per la via di write permission:
Per automatizzazioni solitamente i workflow di github vanno molto bene qui.
Io ho un servizio privato(privato perché lo ho scritto molto da cani xD su mie necessità ) che ho scritto io e workflow che esportano dal mio obsidian e vanno sul mio sito https://flecart.github.io/notes ad ogni push.

Ti posso dare accesso a quello e aiutarti a settare il workflow.

2024-03-15 19:35 UTC, Flecart commented
Pensandoci nattimo la parte che non c'è assumendo di avere le mie cose e il distributore di note. Deve capire quella nota cambiata a che repo appartiene e pusharli lì

2024-03-15 22:04 UTC, samuelemusiani commented
Io sinceramente eviterei di fare tantissimi commit perché le note vengono continuamente aggiornate. Caricherei quelle che sono già concluse e non devono essere modificate se non per correggere errori che saltano fuori perché qualcuno li segnala. Se alcuni appunti non sono conclusi puoi aspettare a caricarli e farlo quando sono finiti :)

2024-04-22 15:21 UTC, Flecart commented
Sembra sia stato deciso di mandare commit solo delle note di interesse.

2024-04-22 15:21 UTC, closed without merging